#' FScore_group Calculates the FScore value for a group given a particular class
#'
#' @param class Vector with the actual kinds of individuals. All individuals must have an assigned class
#' @param confusion_matrix Matrix of confusion between the actual classes and the classes generated by the clustering method.
#' @param class_to_calculate Indicates the class with respect to which it will calculate the FScore
#' @return Real number representing the group FScore. This value is between the range [0,1]
#' 
FScore_group <- function(class = NULL, confusion_matrix = NULL, number_group = NULL, class_to_calculate = NULL)
{
  if(is.null(class))
  {
    stop("'class' must be a vector with individual class")
  }
  
  if(is.null(confusion_matrix))
  {
    stop("'confusion_matrix' must be a confusion matrix")
  }
  
  if(is.null(number_group))
  {
    stop("'number_group' must be a integer number")
  }
  
  if(is.null(class_to_calculate))
  {
    stop("'class_to_calculate' must be a integer number")
  }
  
  fscore <- 0
  
  if(sum(confusion_matrix[ ,number_group]) != 0)
  {
    precision <- confusion_matrix[class_to_calculate, number_group]/sum(confusion_matrix[ ,number_group])
  }else
  {
    precision <- 0
  }
  
  if(!is.na(table(class)[class_to_calculate]))
  {
    recall <- confusion_matrix[class_to_calculate, number_group]/table(class)[class_to_calculate]
  }else
  {
    recall <- 0
  }
  
  if((precision + recall) != 0)
  {
    fscore <- (2*precision*recall) / (precision + recall)
  }
  
  return (fscore)
}




#' Calculates the FScore for a complete grouping hierarchy.
#' This algorithm is the implementation of the metric proposed in 
#' "Fast and Effective Text Mining Using Linear-time Document Clustering" por Bjornar Larsen and Chinatsu Aone
#' 
#' @param class Vector with the actual kinds of individuals. All individuals must have an assigned class
#' @param tree Object of the "hclust" class.
#'
#' @return Real number representing hierarchical FScore. This value is between the range [0,1]
#'
FScore_hierarchical_clustering <- function(class = NULL, tree = NULL)
{
  if(is.null(class))
  {
    stop("'class' must be a vector with individual class")
  }
  
  if(is.null(tree))
  {
    stop("'tree' must be a hclust object")
  }
  
  # It contains the groups formed in the tree at the different levels of hierarchy.
  
  cutree_matrix <- cutree(tree, 1:length(class), NULL)
  
  # It contains the maximum FScore obtained for the whole hierarchy with respect to each of the classes
  fscores_to_class <- rep(0, length(table(class)))
  
  # Calculate the fscore for each group's tree with respect to each of the classes
  for(i in 1:ncol(cutree_matrix))    
  {
    table_groups <- table(cutree_matrix[,i])
    confusion <- table(class, cutree_matrix[,i])   
    
    # All groups that exist at a cut-off level of the hierarchy
    for(j in 1:length(table_groups))
    {
      for(k in 1:length(table(class))) 
      {
            fscore_group_n <- FScore_group(class = class, confusion_matrix = confusion, names(table_groups[j]), class_to_calculate = k)
            fscores_to_class[k] <- max(fscores_to_class[k], fscore_group_n)
      }
    }
  }
  
  fscore_hierarchical <- 0
  for(k in 1:length(table(class)))
  {
    fscore_hierarchical <- fscore_hierarchical + (table(class)[k]*fscores_to_class[k])/length(class)     
  }
  
  return (fscore_hierarchical)
}






#' Calculates the FScore for a given group number.
#' This algorithm is the implementation of the metric proposed in 
#' "Fast and Effective Text Mining Using Linear-time Document Clustering" por Bjornar Larsen and Chinatsu Aone
#' 
#' @param class Vector with the actual kinds of individuals. All individuals must have an assigned class
#' @param tree Object of the "hclust" class.
#' @param group_number -number of specific group.
#' 
#' @return Real number representing hierarchical FScore. This value is between the range [0,1]
#'
FScore_Group_clustering <- function(class = NULL, tree = NULL, group_number = NULL)
{
  if(is.null(class))
  {
    stop("'class' must be a vector with individual class")
  }
  
  if(is.null(tree))
  {
    stop("'tree' must be a hclust object")
  }
  
  # It contains the groups formed in the tree at the different levels of hierarchy.
  
  cutree_matrix <- cutree(tree, 1:length(class), NULL)
  
  # It contains the maximum FScore obtained for the whole hierarchy with respect to each of the classes
  fscores_to_class <- rep(0, length(table(class)))
  
  # Calculate the fscore for each group's tree with respect to each of the classes
 # for(i in 1:ncol(cutree_matrix))    
 # {
    #table_groups <- table(cutree_matrix[,i])
    table_groups <- table(cutree_matrix[,group_number])
    confusion <- table(class, cutree_matrix[,group_number])   
    
    # All groups that exist at a cut-off level of the hierarchy
    for(j in 1:length(table_groups))
    {
      for(k in 1:length(table(class))) 
      {
        fscore_group_n <- FScore_group(class = class, confusion_matrix = confusion, names(table_groups[j]), class_to_calculate = k)
        fscores_to_class[k] <- max(fscores_to_class[k], fscore_group_n)
      }
    }
 # }
  
 # fscore_hierarchical <- 0
 # for(k in 1:length(table(class)))
 # {
 #   fscore_hierarchical <- fscore_hierarchical + (table(class)[k]*fscores_to_class[k])/length(class)     
 # }
  
  return (fscore_group_n)
}


#' Returns cluster group for given number.
#
#' 
#' @param class Vector with the actual kinds of individuals. All individuals must have an assigned class
#' @param tree Object of the "hclust" class.
#' @param group_number -number of specific group.
#' 
#' @return Real number representing hierarchical FScore. This value is between the range [0,1]

Get_Group_By_Number <- function(class = NULL, tree = NULL, group_number = NULL)
{
  
  if(is.null(class))
  {
    stop("'class' must be a vector with individual class")
  }
  
  if(is.null(tree))
  {
    stop("'tree' must be a hclust object")
  }
  
  # It contains the groups formed in the tree at the different levels of hierarchy.
  
  cutree_matrix <- cutree(tree, 1:length(class), NULL)
  
  rezult <- c()
  rezult <- cutree_matrix[ ,group_number]
  
  return(rezult)

}






